/** LeetCode 面试经典 150 题 — 中文版 23 模块题单（单一数据源） */

export const PLAN_URL = 'https://leetcode.cn/studyplan/top-interview-150/';

export const modules = [
  {
    id: '01',
    file: '01-array-string',
    postId: 'top150-01-array-string',
    title: '数组 / 字符串',
    titleShort: '数组与字符串',
    tags: ['Top150', '数组', '字符串'],
    summary: '数组操作、字符串处理、贪心与双指针思想在数组上的应用。',
    problems: [
      { num: 88, slug: 'merge-sorted-array', titleZh: '合并两个有序数组', difficulty: '简单' },
      { num: 27, slug: 'remove-element', titleZh: '移除元素', difficulty: '简单' },
      { num: 26, slug: 'remove-duplicates-from-sorted-array', titleZh: '删除有序数组中的重复项', difficulty: '简单' },
      { num: 80, slug: 'remove-duplicates-from-sorted-array-ii', titleZh: '删除有序数组中的重复项 II', difficulty: '中等' },
      { num: 169, slug: 'majority-element', titleZh: '多数元素', difficulty: '简单' },
      { num: 189, slug: 'rotate-array', titleZh: '轮转数组', difficulty: '中等' },
      { num: 121, slug: 'best-time-to-buy-and-sell-stock', titleZh: '买卖股票的最佳时机', difficulty: '简单' },
      { num: 122, slug: 'best-time-to-buy-and-sell-stock-ii', titleZh: '买卖股票的最佳时机 II', difficulty: '中等' },
      { num: 55, slug: 'jump-game', titleZh: '跳跃游戏', difficulty: '中等' },
      { num: 45, slug: 'jump-game-ii', titleZh: '跳跃游戏 II', difficulty: '中等' },
      { num: 274, slug: 'h-index', titleZh: 'H 指数', difficulty: '中等' },
      { num: 380, slug: 'insert-delete-getrandom-o1', titleZh: 'O(1) 时间插入、删除和获取随机元素', difficulty: '中等' },
      { num: 238, slug: 'product-of-array-except-self', titleZh: '除了自身以外数组的乘积', difficulty: '中等' },
      { num: 134, slug: 'gas-station', titleZh: '加油站', difficulty: '中等' },
      { num: 135, slug: 'candy', titleZh: '分发糖果', difficulty: '困难' },
      { num: 42, slug: 'trapping-rain-water', titleZh: '接雨水', difficulty: '困难' },
      { num: 13, slug: 'roman-to-integer', titleZh: '罗马数字转整数', difficulty: '简单' },
      { num: 12, slug: 'integer-to-roman', titleZh: '整数转罗马数字', difficulty: '中等' },
      { num: 58, slug: 'length-of-last-word', titleZh: '最后一个单词的长度', difficulty: '简单' },
      { num: 14, slug: 'longest-common-prefix', titleZh: '最长公共前缀', difficulty: '简单' },
      { num: 151, slug: 'reverse-words-in-a-string', titleZh: '反转字符串中的单词', difficulty: '中等' },
      { num: 6, slug: 'zigzag-conversion', titleZh: 'Z 字形变换', difficulty: '中等' },
      { num: 28, slug: 'find-the-index-of-the-first-occurrence-in-a-string', titleZh: '找出字符串中第一个匹配项的下标', difficulty: '简单' },
      { num: 68, slug: 'text-justification', titleZh: '文本左右对齐', difficulty: '困难' },
    ],
  },
  {
    id: '02',
    file: '02-two-pointers',
    postId: 'top150-02-two-pointers',
    title: '双指针',
    titleShort: '双指针',
    tags: ['Top150', '双指针'],
    summary: '左右指针、快慢指针在有序数组与字符串上的经典应用。',
    problems: [
      { num: 125, slug: 'valid-palindrome', titleZh: '验证回文串', difficulty: '简单' },
      { num: 392, slug: 'is-subsequence', titleZh: '判断子序列', difficulty: '简单' },
      { num: 167, slug: 'two-sum-ii-input-array-is-sorted', titleZh: '两数之和 II - 输入有序数组', difficulty: '中等' },
      { num: 11, slug: 'container-with-most-water', titleZh: '盛最多水的容器', difficulty: '中等' },
      { num: 15, slug: '3sum', titleZh: '三数之和', difficulty: '中等' },
    ],
  },
  {
    id: '03',
    file: '03-sliding-window',
    postId: 'top150-03-sliding-window',
    title: '滑动窗口',
    titleShort: '滑动窗口',
    tags: ['Top150', '滑动窗口'],
    summary: '固定/可变窗口维护区间状态，处理子数组与子串问题。',
    problems: [
      { num: 209, slug: 'minimum-size-subarray-sum', titleZh: '长度最小的子数组', difficulty: '中等' },
      { num: 3, slug: 'longest-substring-without-repeating-characters', titleZh: '无重复字符的最长子串', difficulty: '中等' },
      { num: 30, slug: 'substring-with-concatenation-of-all-words', titleZh: '串联所有单词的子串', difficulty: '困难' },
      { num: 76, slug: 'minimum-window-substring', titleZh: '最小覆盖子串', difficulty: '困难' },
    ],
  },
  {
    id: '04',
    file: '04-matrix',
    postId: 'top150-04-matrix',
    title: '矩阵',
    titleShort: '矩阵',
    tags: ['Top150', '矩阵'],
    summary: '二维数组遍历、原地变换与模拟类问题。',
    problems: [
      { num: 36, slug: 'valid-sudoku', titleZh: '有效的数独', difficulty: '中等' },
      { num: 54, slug: 'spiral-matrix', titleZh: '螺旋矩阵', difficulty: '中等' },
      { num: 48, slug: 'rotate-image', titleZh: '旋转图像', difficulty: '中等' },
      { num: 73, slug: 'set-matrix-zeroes', titleZh: '矩阵置零', difficulty: '中等' },
      { num: 289, slug: 'game-of-life', titleZh: '生命游戏', difficulty: '中等' },
    ],
  },
  {
    id: '05',
    file: '05-hashmap',
    postId: 'top150-05-hashmap',
    title: '哈希表',
    titleShort: '哈希表',
    tags: ['Top150', '哈希表'],
    summary: '哈希映射计数、分组与 O(1) 查找，含快乐数等经典题。',
    problems: [
      { num: 383, slug: 'ransom-note', titleZh: '赎金信', difficulty: '简单' },
      { num: 205, slug: 'isomorphic-strings', titleZh: '同构字符串', difficulty: '简单' },
      { num: 290, slug: 'word-pattern', titleZh: '单词规律', difficulty: '简单' },
      { num: 242, slug: 'valid-anagram', titleZh: '有效的字母异位词', difficulty: '简单' },
      { num: 49, slug: 'group-anagrams', titleZh: '字母异位词分组', difficulty: '中等' },
      { num: 1, slug: 'two-sum', titleZh: '两数之和', difficulty: '简单' },
      { num: 202, slug: 'happy-number', titleZh: '快乐数', difficulty: '简单' },
      { num: 219, slug: 'contains-duplicate-ii', titleZh: '存在重复元素 II', difficulty: '简单' },
      { num: 128, slug: 'longest-consecutive-sequence', titleZh: '最长连续序列', difficulty: '中等' },
    ],
  },
  {
    id: '06',
    file: '06-intervals',
    postId: 'top150-06-intervals',
    title: '区间',
    titleShort: '区间',
    tags: ['Top150', '区间'],
    summary: '区间合并、插入与贪心选点。',
    problems: [
      { num: 228, slug: 'summary-ranges', titleZh: '汇总区间', difficulty: '简单' },
      { num: 56, slug: 'merge-intervals', titleZh: '合并区间', difficulty: '中等' },
      { num: 57, slug: 'insert-interval', titleZh: '插入区间', difficulty: '中等' },
      { num: 452, slug: 'minimum-number-of-arrows-to-burst-balloons', titleZh: '用最少数量的箭引爆气球', difficulty: '中等' },
    ],
  },
  {
    id: '07',
    file: '07-stack',
    postId: 'top150-07-stack',
    title: '栈',
    titleShort: '栈',
    tags: ['Top150', '栈'],
    summary: '括号匹配、单调栈思想与表达式求值。',
    problems: [
      { num: 20, slug: 'valid-parentheses', titleZh: '有效的括号', difficulty: '简单' },
      { num: 71, slug: 'simplify-path', titleZh: '简化路径', difficulty: '中等' },
      { num: 155, slug: 'min-stack', titleZh: '最小栈', difficulty: '中等' },
      { num: 150, slug: 'evaluate-reverse-polish-notation', titleZh: '逆波兰表达式求值', difficulty: '中等' },
      { num: 224, slug: 'basic-calculator', titleZh: '基本计算器', difficulty: '困难' },
    ],
  },
  {
    id: '08',
    file: '08-linked-list',
    postId: 'top150-08-linked-list',
    title: '链表',
    titleShort: '链表',
    tags: ['Top150', '链表'],
    summary: '虚拟头节点、快慢指针、反转与 LRU 设计。',
    problems: [
      { num: 141, slug: 'linked-list-cycle', titleZh: '环形链表', difficulty: '简单' },
      { num: 2, slug: 'add-two-numbers', titleZh: '两数相加', difficulty: '中等' },
      { num: 21, slug: 'merge-two-sorted-lists', titleZh: '合并两个有序链表', difficulty: '简单' },
      { num: 138, slug: 'copy-list-with-random-pointer', titleZh: '随机链表的复制', difficulty: '中等' },
      { num: 92, slug: 'reverse-linked-list-ii', titleZh: '反转链表 II', difficulty: '中等' },
      { num: 25, slug: 'reverse-nodes-in-k-group', titleZh: 'K 个一组翻转链表', difficulty: '困难' },
      { num: 19, slug: 'remove-nth-node-from-end-of-list', titleZh: '删除链表的倒数第 N 个结点', difficulty: '中等' },
      { num: 82, slug: 'remove-duplicates-from-sorted-list-ii', titleZh: '删除排序链表中的重复元素 II', difficulty: '中等' },
      { num: 61, slug: 'rotate-list', titleZh: '旋转链表', difficulty: '中等' },
      { num: 86, slug: 'partition-list', titleZh: '分隔链表', difficulty: '中等' },
      { num: 146, slug: 'lru-cache', titleZh: 'LRU 缓存', difficulty: '中等' },
    ],
  },
  {
    id: '09',
    file: '09-binary-tree',
    postId: 'top150-09-binary-tree',
    title: '二叉树',
    titleShort: '二叉树',
    tags: ['Top150', '二叉树'],
    summary: '递归 DFS、路径问题、建树与树形 DP 基础。',
    problems: [
      { num: 104, slug: 'maximum-depth-of-binary-tree', titleZh: '二叉树的最大深度', difficulty: '简单' },
      { num: 100, slug: 'same-tree', titleZh: '相同的树', difficulty: '简单' },
      { num: 226, slug: 'invert-binary-tree', titleZh: '翻转二叉树', difficulty: '简单' },
      { num: 101, slug: 'symmetric-tree', titleZh: '对称二叉树', difficulty: '简单' },
      { num: 105, slug: 'construct-binary-tree-from-preorder-and-inorder-traversal', titleZh: '从前序与中序遍历序列构造二叉树', difficulty: '中等' },
      { num: 106, slug: 'construct-binary-tree-from-inorder-and-postorder-traversal', titleZh: '从中序与后序遍历序列构造二叉树', difficulty: '中等' },
      { num: 117, slug: 'populating-next-right-pointers-in-each-node-ii', titleZh: '填充每个节点的下一个右侧节点指针 II', difficulty: '中等' },
      { num: 114, slug: 'flatten-binary-tree-to-linked-list', titleZh: '二叉树展开为链表', difficulty: '中等' },
      { num: 112, slug: 'path-sum', titleZh: '路径总和', difficulty: '简单' },
      { num: 129, slug: 'sum-root-to-leaf-numbers', titleZh: '求根节点到叶节点数字之和', difficulty: '中等' },
      { num: 124, slug: 'binary-tree-maximum-path-sum', titleZh: '二叉树中的最大路径和', difficulty: '困难' },
      { num: 173, slug: 'binary-search-tree-iterator', titleZh: '二叉搜索树迭代器', difficulty: '中等' },
      { num: 222, slug: 'count-complete-tree-nodes', titleZh: '完全二叉树的节点个数', difficulty: '简单' },
      { num: 236, slug: 'lowest-common-ancestor-of-a-binary-tree', titleZh: '二叉树的最近公共祖先', difficulty: '中等' },
    ],
  },
  {
    id: '10',
    file: '10-binary-tree-bfs',
    postId: 'top150-10-binary-tree-bfs',
    title: '二叉树层次遍历',
    titleShort: '二叉树层次遍历',
    tags: ['Top150', '二叉树', 'BFS'],
    summary: '层序遍历、锯齿层序与按层统计。',
    problems: [
      { num: 199, slug: 'binary-tree-right-side-view', titleZh: '二叉树的右视图', difficulty: '中等' },
      { num: 637, slug: 'average-of-levels-in-binary-tree', titleZh: '二叉树的层平均值', difficulty: '简单' },
      { num: 102, slug: 'binary-tree-level-order-traversal', titleZh: '二叉树的层序遍历', difficulty: '中等' },
      { num: 103, slug: 'binary-tree-zigzag-level-order-traversal', titleZh: '二叉树的锯齿形层序遍历', difficulty: '中等' },
    ],
  },
  {
    id: '11',
    file: '11-binary-search-tree',
    postId: 'top150-11-binary-search-tree',
    title: '二叉搜索树',
    titleShort: '二叉搜索树',
    tags: ['Top150', '二叉搜索树'],
    summary: 'BST 中序性质、验证与第 K 小元素。',
    problems: [
      { num: 530, slug: 'minimum-absolute-difference-in-bst', titleZh: '二叉搜索树的最小绝对差', difficulty: '简单' },
      { num: 230, slug: 'kth-smallest-element-in-a-bst', titleZh: '二叉搜索树中第 K 小的元素', difficulty: '中等' },
      { num: 98, slug: 'validate-binary-search-tree', titleZh: '验证二叉搜索树', difficulty: '中等' },
    ],
  },
  {
    id: '12',
    file: '12-graph',
    postId: 'top150-12-graph',
    title: '图',
    titleShort: '图',
    tags: ['Top150', '图'],
    summary: 'DFS/BFS 遍历、并查集思想与拓扑排序。',
    problems: [
      { num: 200, slug: 'number-of-islands', titleZh: '岛屿数量', difficulty: '中等' },
      { num: 130, slug: 'surrounded-regions', titleZh: '被围绕的区域', difficulty: '中等' },
      { num: 133, slug: 'clone-graph', titleZh: '克隆图', difficulty: '中等' },
      { num: 399, slug: 'evaluate-division', titleZh: '除法求值', difficulty: '中等' },
      { num: 207, slug: 'course-schedule', titleZh: '课程表', difficulty: '中等' },
      { num: 210, slug: 'course-schedule-ii', titleZh: '课程表 II', difficulty: '中等' },
    ],
  },
  {
    id: '13',
    file: '13-graph-bfs',
    postId: 'top150-13-graph-bfs',
    title: '图的广度优先搜索',
    titleShort: '图的 BFS',
    tags: ['Top150', '图', 'BFS'],
    summary: '最短步数 BFS：棋盘、基因链与单词接龙。',
    problems: [
      { num: 909, slug: 'snakes-and-ladders', titleZh: '蛇梯棋', difficulty: '中等' },
      { num: 433, slug: 'minimum-genetic-mutation', titleZh: '最小基因变化', difficulty: '中等' },
      { num: 127, slug: 'word-ladder', titleZh: '单词接龙', difficulty: '困难' },
    ],
  },
  {
    id: '14',
    file: '14-trie',
    postId: 'top150-14-trie',
    title: '字典树',
    titleShort: '字典树',
    tags: ['Top150', '字典树', 'Trie'],
    summary: '前缀树实现、带通配符搜索与单词网格搜索。',
    problems: [
      { num: 208, slug: 'implement-trie-prefix-tree', titleZh: '实现 Trie (前缀树)', difficulty: '中等' },
      { num: 211, slug: 'design-add-and-search-words-data-structure', titleZh: '添加与搜索单词 - 数据结构设计', difficulty: '中等' },
      { num: 212, slug: 'word-search-ii', titleZh: '单词搜索 II', difficulty: '困难' },
    ],
  },
  {
    id: '15',
    file: '15-backtracking',
    postId: 'top150-15-backtracking',
    title: '回溯',
    titleShort: '回溯',
    tags: ['Top150', '回溯'],
    summary: '组合、排列、子集与剪枝搜索。',
    problems: [
      { num: 17, slug: 'letter-combinations-of-a-phone-number', titleZh: '电话号码的字母组合', difficulty: '中等' },
      { num: 77, slug: 'combinations', titleZh: '组合', difficulty: '中等' },
      { num: 46, slug: 'permutations', titleZh: '全排列', difficulty: '中等' },
      { num: 39, slug: 'combination-sum', titleZh: '组合总和', difficulty: '中等' },
      { num: 51, slug: 'n-queens-ii', titleZh: 'N 皇后 II', difficulty: '困难' },
      { num: 22, slug: 'generate-parentheses', titleZh: '括号生成', difficulty: '中等' },
      { num: 79, slug: 'word-search', titleZh: '单词搜索', difficulty: '中等' },
    ],
  },
  {
    id: '16',
    file: '16-divide-and-conquer',
    postId: 'top150-16-divide-and-conquer',
    title: '分治',
    titleShort: '分治',
    tags: ['Top150', '分治'],
    summary: '分治合并、归并排序链表与四叉树。',
    problems: [
      { num: 108, slug: 'convert-sorted-array-to-binary-search-tree', titleZh: '将有序数组转换为二叉搜索树', difficulty: '简单' },
      { num: 148, slug: 'sort-list', titleZh: '排序链表', difficulty: '中等' },
      { num: 427, slug: 'construct-quad-tree', titleZh: '建立四叉树', difficulty: '中等' },
      { num: 23, slug: 'merge-k-sorted-lists', titleZh: '合并 K 个升序链表', difficulty: '困难' },
    ],
  },
  {
    id: '17',
    file: '17-kadane',
    postId: 'top150-17-kadane',
    title: 'Kadane 算法',
    titleShort: 'Kadane 算法',
    tags: ['Top150', 'Kadane', '动态规划'],
    summary: '最大子数组和及其环形变体。',
    problems: [
      { num: 53, slug: 'maximum-subarray', titleZh: '最大子数组和', difficulty: '中等' },
      { num: 918, slug: 'maximum-sum-circular-subarray', titleZh: '环形子数组的最大和', difficulty: '中等' },
    ],
  },
  {
    id: '18',
    file: '18-binary-search',
    postId: 'top150-18-binary-search',
    title: '二分查找',
    titleShort: '二分查找',
    tags: ['Top150', '二分查找'],
    summary: '有序数组二分、旋转数组与双数组中位数。',
    problems: [
      { num: 35, slug: 'search-insert-position', titleZh: '搜索插入位置', difficulty: '简单' },
      { num: 74, slug: 'search-a-2d-matrix', titleZh: '搜索二维矩阵', difficulty: '中等' },
      { num: 162, slug: 'find-peak-element', titleZh: '寻找峰值', difficulty: '中等' },
      { num: 33, slug: 'search-in-rotated-sorted-array', titleZh: '搜索旋转排序数组', difficulty: '中等' },
      { num: 34, slug: 'find-first-and-last-position-of-element-in-sorted-array', titleZh: '在排序数组中查找元素的第一个和最后一个位置', difficulty: '中等' },
      { num: 153, slug: 'find-minimum-in-rotated-sorted-array', titleZh: '寻找旋转排序数组中的最小值', difficulty: '中等' },
      { num: 4, slug: 'median-of-two-sorted-arrays', titleZh: '寻找两个正序数组的中位数', difficulty: '困难' },
    ],
  },
  {
    id: '19',
    file: '19-heap',
    postId: 'top150-19-heap',
    title: '堆',
    titleShort: '堆',
    tags: ['Top150', '堆'],
    summary: '优先队列、TopK 与数据流中位数。',
    problems: [
      { num: 215, slug: 'kth-largest-element-in-an-array', titleZh: '数组中的第K个最大元素', difficulty: '中等' },
      { num: 502, slug: 'ipo', titleZh: 'IPO', difficulty: '困难' },
      { num: 373, slug: 'find-k-pairs-with-smallest-sums', titleZh: '查找和最小的 K 对数字', difficulty: '中等' },
      { num: 295, slug: 'find-median-from-data-stream', titleZh: '数据流的中位数', difficulty: '困难' },
    ],
  },
  {
    id: '20',
    file: '20-bit-manipulation',
    postId: 'top150-20-bit-manipulation',
    title: '位运算',
    titleShort: '位运算',
    tags: ['Top150', '位运算'],
    summary: '异或、位计数与区间按位与。',
    problems: [
      { num: 67, slug: 'add-binary', titleZh: '二进制求和', difficulty: '简单' },
      { num: 190, slug: 'reverse-bits', titleZh: '颠倒二进制位', difficulty: '简单' },
      { num: 191, slug: 'number-of-1-bits', titleZh: '位1的个数', difficulty: '简单' },
      { num: 136, slug: 'single-number', titleZh: '只出现一次的数字', difficulty: '简单' },
      { num: 137, slug: 'single-number-ii', titleZh: '只出现一次的数字 II', difficulty: '中等' },
      { num: 201, slug: 'bitwise-and-of-numbers-range', titleZh: '数字范围按位与', difficulty: '中等' },
    ],
  },
  {
    id: '21',
    file: '21-math',
    postId: 'top150-21-math',
    title: '数学',
    titleShort: '数学',
    tags: ['Top150', '数学'],
    summary: '数论、快速幂与几何计数。',
    problems: [
      { num: 9, slug: 'palindrome-number', titleZh: '回文数', difficulty: '简单' },
      { num: 66, slug: 'plus-one', titleZh: '加一', difficulty: '简单' },
      { num: 172, slug: 'factorial-trailing-zeroes', titleZh: '阶乘后的零', difficulty: '中等' },
      { num: 69, slug: 'sqrtx', titleZh: 'x 的平方根', difficulty: '简单' },
      { num: 50, slug: 'powx-n', titleZh: 'Pow(x, n)', difficulty: '中等' },
      { num: 149, slug: 'max-points-on-a-line', titleZh: '直线上最多的点数', difficulty: '困难' },
    ],
  },
  {
    id: '22',
    file: '22-1d-dp',
    postId: 'top150-22-1d-dp',
    title: '一维动态规划',
    titleShort: '一维动态规划',
    tags: ['Top150', '动态规划', '一维DP'],
    summary: '线性 DP：爬楼梯、打家劫舍、零钱兑换与 LIS。',
    problems: [
      { num: 70, slug: 'climbing-stairs', titleZh: '爬楼梯', difficulty: '简单' },
      { num: 198, slug: 'house-robber', titleZh: '打家劫舍', difficulty: '中等' },
      { num: 139, slug: 'word-break', titleZh: '单词拆分', difficulty: '中等' },
      { num: 322, slug: 'coin-change', titleZh: '零钱兑换', difficulty: '中等' },
      { num: 300, slug: 'longest-increasing-subsequence', titleZh: '最长递增子序列', difficulty: '中等' },
    ],
  },
  {
    id: '23',
    file: '23-multidimensional-dp',
    postId: 'top150-23-multidimensional-dp',
    title: '多维动态规划',
    titleShort: '多维动态规划',
    tags: ['Top150', '动态规划', '多维DP'],
    summary: '二维 DP、编辑距离、股票系列与最大正方形。',
    problems: [
      { num: 120, slug: 'triangle', titleZh: '三角形最小路径和', difficulty: '中等' },
      { num: 64, slug: 'minimum-path-sum', titleZh: '最小路径和', difficulty: '中等' },
      { num: 63, slug: 'unique-paths-ii', titleZh: '不同路径 II', difficulty: '中等' },
      { num: 5, slug: 'longest-palindromic-substring', titleZh: '最长回文子串', difficulty: '中等' },
      { num: 97, slug: 'interleaving-string', titleZh: '交错字符串', difficulty: '中等' },
      { num: 72, slug: 'edit-distance', titleZh: '编辑距离', difficulty: '中等' },
      { num: 123, slug: 'best-time-to-buy-and-sell-stock-iii', titleZh: '买卖股票的最佳时机 III', difficulty: '困难' },
      { num: 188, slug: 'best-time-to-buy-and-sell-stock-iv', titleZh: '买卖股票的最佳时机 IV', difficulty: '困难' },
      { num: 221, slug: 'maximal-square', titleZh: '最大正方形', difficulty: '中等' },
    ],
  },
];

export const totalProblems = modules.reduce((n, m) => n + m.problems.length, 0);
